__title__ = 'dtanys'
__description__ = 'Python structured data parser.'
__url__ = 'https://github.com/luxuncang/dtanys'
__version__ = '1.0.5'
__author__ = 'ShengXin Lu'
__author_email__ = 'luxuncang@qq.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2021 ShengXin Lu'